import Link from 'next/link'
import {createServerSupabase} from '@/lib/supabase'
export default async function Admin(){
 const s=await createServerSupabase();const{data:{user}}=await s.auth.getUser();if(!user)return <main className="shell"><div className="card">Log in to access admin.</div></main>
 const{data:p}=await s.from('profiles').select('is_admin,username').eq('id',user.id).single();if(!p?.is_admin)return <main className="shell"><div className="card">Admin access denied.</div></main>
 const [subs,products,orders,users,flags,appeals,tasks,rentals]=await Promise.all([
  s.from('seller_submissions').select('id,title,status,ai_state,quality_score,risk_score,created_at').order('created_at',{ascending:false}).limit(30),
  s.from('products').select('*',{count:'exact',head:true}),s.from('orders').select('*',{count:'exact',head:true}),s.from('profiles').select('*',{count:'exact',head:true}),s.from('moderation_flags').select('*',{count:'exact',head:true}).eq('resolved',false),s.from('appeals').select('*',{count:'exact',head:true}).eq('status','open'),s.from('ai_tasks').select('*',{count:'exact',head:true}).eq('status','queued'),s.from('rental_listings').select('*',{count:'exact',head:true}).eq('status','pending_admin')])
 return <main className="shell"><nav className="nav"><div className="brand">DIGITAL <span>SALVAGE</span></div><Link href="/">Exit admin</Link></nav><section className="card wide"><div className="eyebrow">CONTROL CENTER</div><h1>Admin command room</h1><p className="muted">Review AI evidence, approve content, manage safety actions and control the site.</p><div className="grid3">{[['Submissions',subs.data?.length||0],['Listings',products.count||0],['Orders',orders.count||0],['Users',users.count||0],['Open flags',flags.count||0],['Appeals',appeals.count||0],['AI queue',tasks.count||0],['Rental approvals',rentals.count||0]].map(x=><div className="card soft" key={String(x[0])}><div className="stat">{x[1]}</div><p className="muted">{x[0]}</p></div>)}</div></section><section className="card wide"><h2>Latest seller submissions</h2>{!subs.data?.length?<p className="muted">No submissions yet.</p>:subs.data.map(r=><div className="row" key={r.id}><div><b>{r.title}</b><small>{r.status} · AI {r.ai_state}</small></div><span>{r.quality_score??'—'} quality · {r.risk_score??'—'} risk</span></div>)}</section><section className="card wide"><h2>Admin areas</h2><div className="chips">{['Users','Sellers','Submissions','AI reports','Quality flags','Payments','Orders','Appeals','Bans','Referrals','Royalties','Payouts','Support','Reviews','Rentals','Moderators','Permissions','Site upgrades','Versions','Ads','Diagnostics','Settings','Audit logs'].map(x=><span key={x}>{x}</span>)}</div></section></main>
}