import Link from 'next/link';

export type LegalPageKey = 'terms'|'privacy'|'seller-agreement'|'buyer-agreement'|'refund-policy'|'copyright-ip'|'acceptable-use'|'download-license'|'rental-agreement'|'social-media-access'|'referral-policy';

const pages: Record<LegalPageKey,{title:string;intro:string;sections:Array<[string,string]>}> = {
  terms:{title:'Terms of Service',intro:'Rules for using the EarnEffortlessly marketplace and related services.',sections:[['Using the marketplace','Use the service lawfully, provide accurate account information, and do not attempt to bypass security, permissions, payment verification, or access controls.'],['Digital goods','Only lawful digital goods may be listed. Stolen, pirated, leaked, hacked, or otherwise unauthorized material is prohibited.'],['Accounts','Users are responsible for activity performed through their account and must protect their login credentials.'],['Enforcement','Listings or accounts may be restricted, suspended, or removed when required by policy, security, legal obligations, or abuse prevention.'],['Changes','Policies may be updated as the service evolves. The current published version applies to future activity after it is posted.']]},
  privacy:{title:'Privacy Policy',intro:'A plain-language overview of how account and marketplace data is handled.',sections:[['Data we use','The service may process account details, profile information, marketplace activity, orders, submissions, support messages, reports, and security/audit events needed to operate the platform.'],['Security','Secrets and privileged credentials must remain server-side. OAuth access tokens are intended to be stored securely and never exposed to frontend JavaScript.'],['Social connections','When an official OAuth integration is connected, the platform stores the minimum authorization metadata needed to operate the approved integration and keeps credentials server-side.'],['Retention','Financial, audit, security, and ownership records may need to be retained to preserve history, resolve disputes, and meet legal obligations.'],['Your controls','Account settings should provide available controls for profile, password, sessions, notifications, privacy, communication preferences, and account deletion/deactivation.']]},
  'seller-agreement':{title:'Seller Agreement',intro:'Requirements for creators and sellers submitting products.',sections:[['Ownership','You must have the rights required to sell or license the submitted content.'],['Submission review','Submissions may be checked for completeness, technical integrity, quality, originality/copyright risk, security risk, and marketplace policy compliance.'],['Accuracy','Descriptions, previews, compatibility claims, pricing, and licensing terms must be truthful and kept current.'],['Royalties','Eligible sales may create royalty ledger entries. Manual seller payments are recorded separately from the underlying financial history.'],['Restrictions','Repeated abuse, fraud, infringement, malicious files, or serious policy violations may result in suspension or removal.']]},
  'buyer-agreement':{title:'Buyer Agreement',intro:'Rules governing purchases and access to digital products.',sections:[['Purchase','A purchase creates durable ownership/access records through the order and order-item history.'],['License','Buyers must follow the product license shown before and after purchase, including commercial-use, attribution, redistribution, and modification restrictions where applicable.'],['Downloads','Protected downloads are issued only after the order reaches the required verified payment state.'],['Reviews','Reviews should reflect genuine use or purchase experience and must not be used for abuse, manipulation, or unlawful content.']]},
  'refund-policy':{title:'Refund Policy',intro:'How refunds and related access or royalty adjustments are handled.',sections:[['Record preservation','A refund does not erase the original order or financial history.'],['Access','Where supported, download/access rights may be revoked or adjusted after a refund.'],['Royalties','A refund can reverse or adjust related royalty calculations while preserving the audit trail.'],['Partial refunds','Partial refunds may be supported for eligible situations.'],['Review','Refund decisions should consider the product state, transaction history, evidence, and applicable marketplace rules.']]},
  'copyright-ip':{title:'Copyright & IP Policy',intro:'Protection for lawful ownership and licensed use of marketplace content.',sections:[['Allowed content','Only original, licensed, or otherwise lawfully distributable material may be submitted.'],['Prohibited content','Pirated, stolen, leaked, hacked, or knowingly infringing material is prohibited.'],['Reports','Users can report copyright/IP concerns through the reporting system.'],['Enforcement','The platform may remove or restrict disputed content, preserve relevant evidence, and take account action where appropriate.'],['Disputes','Submit clear ownership or licensing evidence when appealing an enforcement decision.']]},
  'acceptable-use':{title:'Acceptable Use Policy',intro:'Activities that are not allowed on the platform.',sections:[['Security abuse','Do not bypass authentication, CAPTCHA, access controls, rate limits, malware defenses, or platform permissions.'],['Fraud','Do not manipulate payments, referrals, royalties, reviews, ratings, download access, or account ownership.'],['Malicious content','Do not submit malware, destructive code, credential theft tools, or content intended to compromise users or systems.'],['Abuse','Do not harass, impersonate, threaten, spam, or use automation to evade platform controls.']]},
  'download-license':{title:'Download & License Policy',intro:'How digital access and licensing work after purchase.',sections:[['Protected delivery','Digital files are kept in private storage and delivered through authorized, temporary access rather than public file URLs.'],['License visibility','The applicable license is shown to the buyer and remains available in the buyer library.'],['Versioning','The buyer library can show the latest available version and download history where the product supports version updates.'],['Unauthorized sharing','Redistribution or sharing outside the product license is prohibited.']]},
  'rental-agreement':{title:'Rental Agreement',intro:'Rules for supported social-account rental listings.',sections:[['Scope','Only supported social-media accounts may be offered as rentals, and the seller must be the authorized owner/controller.'],['Duration','A standard rental is one full day unless the product rules state otherwise.'],['Delegated access','Where a platform officially supports delegated or manager access, the system may grant and later revoke that access.'],['Safety','Do not delete the owner’s prior content or attempt destructive actions. Such actions may trigger immediate removal of delegated control and moderation.'],['Passwords','Never store or exchange social-media passwords through the rental system.']]},
  'social-media-access':{title:'Social Media Access Policy',intro:'Rules for official social integrations and connected properties.',sections:[['Official integrations only','Use official OAuth/API integrations. Never bypass login, CAPTCHA, platform restrictions, or permission checks.'],['Server-side secrets','Access tokens are intended to remain server-side and protected. They must not be exposed to browser JavaScript.'],['Permission boundaries','The system may act only on explicitly connected properties and actions permitted by the connected account.'],['Unsupported capability','If an official API does not support an action, the service must show that the capability is not supported rather than fabricate support.']]},
  'referral-policy':{title:'Referral Policy',intro:'Rules for referral rewards and related royalty calculations.',sections:[['Referral identity','Each username can have a unique referral code.'],['Referred-user reward','A referred user may receive the configured introductory royalty bonus for the first five submitted contents each month, subject to the marketplace rules.'],['Referrer reward','A referrer may receive the configured lifetime royalty share when eligible activity is attributed to the referral.'],['Integrity','Referral activity must not be fabricated, self-manipulated, spammed, or used to bypass account or financial controls.'],['Reporting','Referral and royalty calculations should appear in the applicable financial reporting and audit history.']]},
};

export default function LegalPage({page}:{page:LegalPageKey}){
 const p=pages[page];
 return <main className='container narrow'><p><Link href='/'>← Home</Link></p><div className='eyebrow'>POLICY</div><h1>{p.title}</h1><p className='muted'>{p.intro}</p><section className='card wide'>{p.sections.map(([h,b])=><article key={h} className='policy-section'><h2>{h}</h2><p>{b}</p></article>)}</section><p className='muted'>These pages describe product behavior and policy structure. They are not legal advice and should be reviewed before final public launch.</p></main>;
}
