export type Indicator={code:string;family:string;severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';label:string;explanation:string};
const r=(code:string,family:string,severity:Indicator['severity'],label:string,explanation:string):Indicator=>({code,family,severity,label,explanation});
export const INDICATORS:Indicator[]=[
 r('EXTENSION_MAGIC_MISMATCH','integrity','CRITICAL','File type mismatch','Claimed extension and detected signature disagree.'),
 r('DOUBLE_EXTENSION','integrity','MEDIUM','Double extension','Multiple executable-looking extensions can disguise the true file type.'),
 r('ARCHIVE_PATH_TRAVERSAL','archive','CRITICAL','Archive path traversal','Archive entry names attempt to escape the extraction directory.'),
 r('RIGHT_TO_LEFT_OVERRIDE','social_engineering','MEDIUM','Filename direction override','Unicode direction controls can disguise a dangerous filename.'),
 r('RWX_SECTION','execution','HIGH','Writable + executable section','Can support self-modifying or injected code.'),
 r('HIGH_ENTROPY','obfuscation','MEDIUM','High entropy','Can indicate packing/encryption; never malicious by itself.'),
 r('PACKER_SIGNATURE','obfuscation','MEDIUM','Packer/cryptor indicator','Known packing/crypting signature requires deeper inspection.'),
 r('DYNAMIC_API_RESOLUTION','evasion','MEDIUM','Dynamic API resolution','Loader APIs may hide runtime capabilities.'),
 r('OBFUSCATED_CODE','obfuscation','HIGH','Obfuscated code','Heavy decode/eval/exec/string-reconstruction patterns reduce transparency and can hide payloads.'),
 r('SUSPICIOUS_BLOB','obfuscation','MEDIUM','Suspicious encoded blob','Large base64/hex-like blobs without clear context may conceal further code.'),
 r('PROCESS_INJECTION_API','execution','CRITICAL','Process injection capability','Remote memory/thread injection indicators found.'),
 r('CREDENTIAL_ACCESS_API','credential_theft','CRITICAL','Credential access capability','Browser/OS secret access indicators found.'),
 r('KEYLOGGING_API','surveillance','CRITICAL','Input/screen surveillance capability','Keyboard, foreground-window or capture APIs found.'),
 r('CLIPBOARD_MONITORING','surveillance','HIGH','Clipboard monitoring','Code accesses clipboard content in a way that can capture sensitive data.'),
 r('C2_NETWORK_API','network','HIGH','Network/C2 capability','Outbound/download/beaconing primitives found.'),
 r('RAW_SOCKET_NETWORK','network','HIGH','Raw socket/network access','Low-level networking can support C2 or exfiltration and needs context review.'),
 r('CLOUD_METADATA_ACCESS','credential_theft','HIGH','Cloud metadata access','Requests to link-local cloud metadata endpoints can expose instance credentials.'),
 r('PERSISTENCE_MECHANISM','persistence','HIGH','Persistence mechanism','Registry/cron/service/startup/scheduled-task persistence indicators found.'),
 r('SECURITY_TAMPERING','evasion','CRITICAL','Security-control tampering','Code attempts to disable or alter security controls.'),
 r('PRIVILEGE_ESCALATION','privilege','CRITICAL','Privilege escalation indicator','Patterns suggest attempts to gain higher privileges.'),
 r('AUTORUN_SCRIPT','persistence','HIGH','Automatic execution script/macro','Auto-open or command-spawning content found.'),
 r('REMOTE_TEMPLATE','document','HIGH','Remote template/object reference','Office content references remote templates/objects that can pull external content.'),
 r('PDF_ACTIVE_CONTENT','document','HIGH','Active PDF content','Automatic action/script/launch feature found.'),
 r('SVG_SCRIPT','web_content','HIGH','Scripted SVG','SVG contains executable JavaScript or script-like content.'),
 r('HTML_IFRAME_REDIRECT','web_content','HIGH','Embedded web redirect','HTML/web content contains iframe or external redirect behavior.'),
 r('POLYGLOT_FILE','integrity','CRITICAL','Polyglot file','The artifact appears to satisfy multiple file-format interpretations.'),
 r('TRACKER_FORM_GRAB','tracking','HIGH','Browser tracking/form capture','DOM form, storage or clipboard interception found.'),
 r('WEBHOOK_EXFIL','exfiltration','HIGH','Webhook/exfiltration endpoint','Known webhook/collection endpoint found.'),
 r('SELF_REPLICATION','execution','CRITICAL','Self-replication behavior','Patterns suggest copying or propagating the payload.'),
 r('C2_POLLING','network','HIGH','Command polling','Repeated remote instruction polling or second-stage retrieval behavior found.'),
 r('LOLBIN_USAGE','execution','HIGH','Living-off-the-land execution','PowerShell/WMI/mshta/regsvr32/rundll32/cmd path found.'),
 r('RANSOMWARE_BEHAVIOR','impact','CRITICAL','Ransomware-like pattern','Bulk encryption/shadow deletion/ransom-note pattern found.'),
 r('ANTI_ANALYSIS','evasion','HIGH','Anti-analysis indicator','VM/sandbox/debugger detection pattern found.'),
 r('INVALID_SIGNATURE','integrity','MEDIUM','Missing/invalid signature','Executable provenance could not be validated.'),
 r('SUSPICIOUS_TIMESTAMP','integrity','LOW','Timestamp anomaly','Timestamp appears inconsistent or manipulated.'),
 r('SYSTEM_LIKE_FILENAME','social_engineering','LOW','System-like filename','Filename mimics trusted system or urgent-document naming.'),
];
const P:[string,RegExp,string][]=[
 ['PROCESS_INJECTION_API',/(VirtualAllocEx|WriteProcessMemory|CreateRemoteThread|NtQueueApcThread|process hollowing)/ig,'process injection'],
 ['CREDENTIAL_ACCESS_API',/(CryptUnprotectData|VaultEnumerateItems|LSASS|Login Data|Web Credentials|browser cookies|password manager|id_rsa|\.aws\/credentials)/ig,'credential access'],
 ['KEYLOGGING_API',/(SetWindowsHookExA|SetWindowsHookExW|GetAsyncKeyState|GetKeyboardState|BitBlt|GetForegroundWindow)/ig,'surveillance'],
 ['CLIPBOARD_MONITORING',/(navigator\.clipboard|clipboardData|GetClipboardData|OpenClipboard)/ig,'clipboard monitoring'],
 ['C2_NETWORK_API',/(InternetOpenA|InternetOpenUrl|WinHttpConnect|WinHttpOpen|URLDownloadToFileA|WSAStartup|socket\s*\(|fetch\s*\(|XMLHttpRequest)/ig,'network/C2'],
 ['CLOUD_METADATA_ACCESS',/(169\.254\.169\.254|metadata\.google\.internal|instance\/metadata)/ig,'cloud metadata access'],
 ['PERSISTENCE_MECHANISM',/(Run\\|RunOnce\\|schtasks(?:\.exe)?\b|crontab\b|systemctl\b|systemd\b|Startup\\)/ig,'persistence'],
 ['SECURITY_TAMPERING',/(DisableAntiSpyware|Set-MpPreference|netsh\s+advfirewall|sc\s+(?:stop|delete)|kill\s+.*defender)/ig,'security tampering'],
 ['PRIVILEGE_ESCALATION',/(sudo\s+|runas\s+|SeDebugPrivilege|token impersonation|setuid\s*\()/ig,'privilege escalation'],
 ['AUTORUN_SCRIPT',/(AutoOpen\s*\(|AutoExec\s*\(|Workbook_Open\s*\(|Document_Open\s*\(|WScript\.Shell|Win32_Process|Shell\s*\(|cmd\.exe|powershell\.exe)/ig,'auto-execution'],
 ['REMOTE_TEMPLATE',/(attachedTemplate|templateURL|remote\s+template|linked\s+OLE|external\s+object)/ig,'remote template/object'],
 ['PDF_ACTIVE_CONTENT',/(\/JS\b|\/JavaScript\b|\/AA\b|\/OpenAction\b|\/Launch\b)/ig,'PDF active content'],
 ['SVG_SCRIPT',/(<script\b|javascript:|onload\s*=|onerror\s*=)/ig,'SVG script'],
 ['HTML_IFRAME_REDIRECT',/(<iframe\b|window\.location\s*=|location\.replace\s*\(|meta\s+http-equiv\s*=\s*[\"\']refresh)/ig,'web redirect'],
 ['TRACKER_FORM_GRAB',/(addEventListener\s*\(\s*[\'\"]submit|localStorage\b|sessionStorage\b|document\.cookie|navigator\.clipboard)/ig,'browser tracking'],
 ['WEBHOOK_EXFIL',/(discord\.com\/api\/webhooks\/|hooks\.slack\.com\/services\/|telegram\.me\/bot)/ig,'webhook exfiltration'],
 ['SELF_REPLICATION',/(copy\s+itself|self-replicat|autorun\.inf|\bworm\b)/ig,'self replication'],
 ['C2_POLLING',/(poll(?:ing)?\s+(?:https?|url)|sleep\s*\(.*\)\s*.*(?:fetch|http|socket)|download(?:ed)?\s+and\s+execute)/ig,'command polling'],
 ['LOLBIN_USAGE',/(powershell(?:\.exe)?\b|wmic\b|wmi(?:\.exe)?\b|mshta(?:\.exe)?\b|regsvr32(?:\.exe)?\b|rundll32(?:\.exe)?\b|cmd(?:\.exe)?\b)/ig,'LOLBIN'],
 ['RANSOMWARE_BEHAVIOR',/(vssadmin(?:\.exe)?\s+delete\s+shadows|delete\s+shadow|encrypt(?:ed|ing)?\s+(?:files|documents)|ransom note|\.wncry\b)/ig,'ransomware'],
 ['ANTI_ANALYSIS',/(IsDebuggerPresent|CheckRemoteDebuggerPresent|VMware|VirtualBox|sandbox|vmx|GetTickCount\s*\(\).*sleep|NtQueryInformationProcess)/ig,'anti-analysis'],
 ['PACKER_SIGNATURE',/(UPX0|UPX1|UPX2|Themida|VMProtect|ASPack|FSG|MEW\b|\.packed\b)/ig,'packer'],
 ['DYNAMIC_API_RESOLUTION',/(LoadLibraryA|LoadLibraryW|GetProcAddress)/ig,'dynamic API resolution'],
 ['OBFUSCATED_CODE',/(\beval\s*\(|\bexec\s*\(|\bFunction\s*\(|base64_decode\s*\(|gzinflate\s*\(|str_rot13\s*\(|atob\s*\(|fromCharCode\s*\(|chr\s*\(|ord\s*\(|(?:[\"\']ev[\"\']\s*\+\s*[\"\']al[\"\'])/ig,'obfuscation/evasion'],
 ['SUSPICIOUS_BLOB',/(?:[A-Za-z0-9+/]{200,}={0,2}|(?:[0-9a-fA-F]{2}){160,})/g,'large encoded blob'],
 ['ARCHIVE_PATH_TRAVERSAL',/(?:\.\.\/|\.\.\\\\|\/etc\/passwd|[A-Za-z]:\\\\)/ig,'archive traversal/path escape'],
 ['RIGHT_TO_LEFT_OVERRIDE',/[\u202A-\u202E\u2066-\u2069]/g,'filename direction override'],
 ['SYSTEM_LIKE_FILENAME',/(?:^|[\\/])(svchost|lsass|wininit|services|invoice|urgent|payment|resume)(?:\.[^.\\/]+)?\.(?:exe|js|vbs|scr|bat|cmd|ps1)$/i,'system-like or deceptive filename'],
];
export function normalizeText(text:string){return text.toLowerCase().normalize('NFKC').replace(/[^\p{L}\p{N}]+/gu,' ').replace(/\s+/g,' ').trim()}
export function tokens(text:string){return [...new Set(normalizeText(text).split(' ').filter(x=>x.length>=3))]}
export function contentScores(title:string,description:string){const words=tokens(`${title} ${description}`);const completeness=Math.min(100,Math.round(description.trim().length/8));const specificity=Math.min(100,Math.round(new Set(words).size/0.6));const spam=/(buy now!!!|guaranteed money|free money|click here|100% free|limited time!!!)/i.test(`${title} ${description}`)?25:0;return {contentScore:Math.max(0,Math.min(100,Math.round(completeness*.55+specificity*.45-spam))),wordCount:words.length,spamPenalty:spam}}
export function inspect(input:{name?:string;extension?:string;mime?:string;magic?:string;entropy?:number;sectionEntropies?:number[];sections?:Array<{characteristics?:string;entropy?:number}>;imports?:string[];exports?:string[];strings?:string[];metadata?:Record<string,unknown>}){const blob=[input.name,input.extension,input.mime,input.magic,...(input.imports??[]),...(input.exports??[]),...(input.strings??[])].filter(Boolean).join('\n');const found:Indicator[]=[];const evidence:Record<string,unknown>={};const add=(c:string,n?:string)=>{const i=INDICATORS.find(x=>x.code===c);if(i&&!found.some(x=>x.code===c)){found.push(i);if(n)evidence[c]=n}};if(input.extension&&input.magic&&/\.(exe|dll|sys)$/i.test(input.extension)&&!/^(MZ|4d5a)/i.test(input.magic))add('EXTENSION_MAGIC_MISMATCH');if(/\.[A-Za-z0-9]{1,6}\.(?:exe|dll|sys|scr|js|vbs|bat|cmd|ps1)$/i.test(String(input.name??'')))add('DOUBLE_EXTENSION');if(typeof input.entropy==='number'&&input.entropy>7.2)add('HIGH_ENTROPY',`overall=${input.entropy}`);if((input.sectionEntropies??[]).some(x=>x>7.5)||(input.sections??[]).some(x=>typeof x.entropy==='number'&&x.entropy>7.5))add('HIGH_ENTROPY','section>7.5');for(const s of input.sections??[])if(/RWX|EXECUTE.*WRITE|WRITE.*EXECUTE/i.test(String(s.characteristics??'')))add('RWX_SECTION');for(const [c,rx,n] of P)if(rx.test(blob))add(c,n);if((input.metadata as any)?.archive_path_traversal===true)add('ARCHIVE_PATH_TRAVERSAL');if((input.metadata as any)?.polyglot===true)add('POLYGLOT_FILE');if((input.metadata as any)?.signature_valid===false)add('INVALID_SIGNATURE');if((input.metadata as any)?.timestamp_anomaly===true)add('SUSPICIOUS_TIMESTAMP');if(/\.(?:exe|dll|sys|scr|js|vbs|bat|cmd|ps1)$/i.test(String(input.name??''))&&/(?:svchost|lsass|wininit|services|invoice|urgent|payment|resume)/i.test(String(input.name??'')))add('SYSTEM_LIKE_FILENAME');const cr=found.filter(x=>x.severity==='CRITICAL').length,hi=found.filter(x=>x.severity==='HIGH').length,me=found.filter(x=>x.severity==='MEDIUM').length,lo=found.filter(x=>x.severity==='LOW').length;const score=Math.min(100,cr*34+hi*18+me*8+lo*2);const level=cr?'CRITICAL':hi>=2||score>=70?'HIGH':me||score>=30?'MEDIUM':lo?'LOW':'INFO';const verdict=cr||score>=80?'REJECTED':score>=35?'REVIEW':'APPROVED';return {indicators:found,evidence,threatScore:score,threatLevel:level,verdict}}
