'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase'
import {FriendlyStatus,NextAction,Timeline} from '@/components/ux-kit'
export default function Seller(){
 const [user,setUser]=useState<any>(null); const [rows,setRows]=useState<any[]>([]); const [profile,setProfile]=useState<any>(null)
 useEffect(()=>{const s=createClient();s.auth.getUser().then(async({data})=>{setUser(data.user);if(data.user){const [a,b]=await Promise.all([s.from('seller_submissions').select('id,title,status,ai_state,quality_score,primary_keyword,created_at').eq('seller_id',data.user.id).order('created_at',{ascending:false}),s.from('profiles').select('username,referral_code,reputation_score').eq('id',data.user.id).single()]);setRows(a.data||[]);setProfile(b.data)}})},[])
 const current=rows[0]
 return <main className="shell"><section className="card wide"><div className="eyebrow">SELLER CENTER</div><h1>Build your inventory.</h1><p className="muted">Explain your content once. The system keeps the inspection, checklist and status visible while you stay in control of the submission.</p><div className="grid2"><div className="card soft"><h2>New content</h2><p>Describe what you have first. Save and return later at any point.</p><Link className="primary" href="/seller/submit">Start submission →</Link></div><div className="card soft"><h2>Your identity</h2><p>Username: <b>{profile?.username||'loading…'}</b></p><p>Referral: <b>{profile?.referral_code||'—'}</b></p><p>Reputation: <b>{profile?.reputation_score??'—'}</b></p></div></div></section>{current?<section className="card wide"><NextAction title={current.status==='changes_requested'?'Update your submission':current.status==='approved'?'Ready for publishing':'Let the system finish the review'} body="You can leave this page safely. Your submission state is stored server-side." href={`/seller/submissions/${current.id}`} label="Open submission"/><Timeline steps={[{title:'Explain',done:true,body:'Your initial description was saved.'},{title:'Upload',done:current.ai_state!=='queued'},{title:'AI inspection',done:['approved','rejected','changes_requested'].includes(current.status),active:['queued','analyzing'].includes(current.ai_state),body:current.ai_state||'Checking'},{title:'Admin decision',active:current.status==='submitted'||current.status==='under_review'},{title:'Publish and earn',active:current.status==='approved'||current.status==='published'}]}/></section>:null}<section className="card wide"><h2>Submission history</h2>{!rows.length?<p className="muted">No submissions yet. Start with the simplest explanation; the required checklist appears as the system understands your content.</p>:rows.map(r=><div className="row" key={r.id}><div><b>{r.title}</b><small>{new Date(r.created_at).toLocaleString()}</small></div><FriendlyStatus status={r.status}/></div>)}</section></main>
}
