'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase';
import Link from 'next/link';

export default function SubmissionDetail({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(''); const [row,setRow]=useState<any>(null); const [report,setReport]=useState<any>(null); const [files,setFiles]=useState<any[]>([]); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('');
 useEffect(()=>{params.then(x=>setId(x.id))},[params]);
 useEffect(()=>{if(!id)return; const s=createClient(); (async()=>{const [a,b,c]=await Promise.all([s.from('seller_submissions').select('*').eq('id',id).single(),s.from('ai_reports').select('*').eq('submission_id',id).order('created_at',{ascending:false}).limit(1).maybeSingle(),s.from('submission_files').select('id,original_name,mime_type,size_bytes,scan_status,created_at').eq('submission_id',id).order('created_at',{ascending:false})]);setRow(a.data);setReport(b.data);setFiles(c.data||[])})()},[id]);
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f||!id)return;setBusy(true);setMsg('Uploading…');const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setMsg('Please sign in.');setBusy(false);return}const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${user.id}/${id}/${crypto.randomUUID()}-${safe}`;const up=await s.storage.from('submission-files').upload(path,f,{upsert:false});if(up.error){setMsg(up.error.message);setBusy(false);return}const ins=await s.from('submission_files').insert({submission_id:id,storage_path:path,original_name:f.name,mime_type:f.type||null,size_bytes:f.size,scan_status:'pending'});setBusy(false);setMsg(ins.error?ins.error.message:'File added. Malware scan is intentionally marked pending until the external scanner is configured.');if(!ins.error)location.reload()}
 if(!row)return <main className='container'><div className='card'>Loading submission…</div></main>;
 const req=row.required_submission?.items||[];
 return <main className='container'><p><Link href='/seller/submissions'>← Submissions</Link></p><div className='card'><span className='badge'>{row.status} · {row.ai_state}</span><h1>{row.title}</h1><p>{row.seller_description}</p><h2>Stage 1 checklist</h2><ul>{req.map((x:string)=><li key={x}>{x}</li>)}</ul><p className='muted'>You can always use “Upload everything”; the AI may correct its first category prediction.</p><input type='file' onChange={upload} disabled={busy}/><div className='notice'>{msg}</div><h2>Submitted files</h2>{files.map(f=><div className='row' key={f.id}><span>{f.original_name}</span><span>{f.mime_type||'unknown'} · {f.scan_status}</span></div>)}<h2>AI inspection</h2>{report?<div><p><b>Quality:</b> {report.quality_label||'pending'} · <b>Safety:</b> {report.safety_label||'pending'}</p><p>{report.summary}</p><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(report.details,null,2)}</pre></div>:<p className='muted'>Inspection report not ready yet.</p>}</div></main>
}
